services:
  db:
    image: timescale/timescaledb:latest-pg15
    container_name: heimdall_db
    restart: always
    environment:
      - POSTGRES_DB=heimdall_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin_password
    ports:
      - "5432:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d

  engine:
    build: .
    container_name: heimdall_engine
    restart: always
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin:admin_password@db:5432/heimdall_db
    ports:
      - "50051:50051"
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db

  grafana:
    image: grafana/grafana:latest
    container_name: heimdall_grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - db
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  timescale_data:
  grafana_data: